name: Test Application

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          echo "Repository checked successfully
                pwd
                ls -R
          
